Add styles fix for new survey button position in rtl
ushahidi/platform-pattern-library pull request #254
Opened 2020-10-26 14:07 UTC by hariclerry

This pull request makes the following changes:
-Adds css code to /assests/sass/utils/_helpers.scss

Testing checklist:
- [x] Yellow new survey button was on the right and text was on the left for RTL
- [x] Yellow new survey button is now on the left and text is on the right RTL
- [x] I certify that I ran my checklist

## Screenshots

#### Screenshot of UI for LTR(English)
<img width="1439" alt="Screenshot 2020-10-23 at 15 10 45" src="https://user-images.githubusercontent.com/12033494/97002719-096c0b80-1543-11eb-822d-652ea52d1953.png">

#### Screenshot of UI for RTL(Arabic)

<img width="1440" alt="Screenshot 2020-10-23 at 15 11 47" src="https://user-images.githubusercontent.com/12033494/97002729-10931980-1543-11eb-9b6f-4c245d4ec1e5.png">

2020-10-27 17:47 UTC, hariclerry commented
Hello @rowasc, can you please this pull request? Thank you.

2020-10-29 11:42 UTC, Angamanga requested changes
See comments in the code :)

2020-10-29 11:42 UTC, Angamanga commented on assets/sass/utils/_helpers.scss
> +.rtl-button-fix {
Sorry I am late on this! We don't need this extra class, we can make use of the same methodology we do in other places in the platform-client. You can read about it here: http://preview.ushahidi.com/platform-pattern-library/master/assets/html/front-end-guidelines/read-direction.html. 

So what we need to do is figure out the right and left positioning of the button in this piece of code: https://github.com/ushahidi/platform-pattern-library/blob/master/assets/sass/5_layouts/_layout-d.scss#L42.

You can see how we handle this in the map-view here: https://github.com/ushahidi/platform-pattern-library/blob/master/assets/sass/4_blocks/_toolbar.scss#L27

I hope this gives you an idea of how to solve it. However well done figuring it out the way you did, this code-base is large and quite complex so its not easy :) Let me know if you need more guidance!

2020-11-02 14:52 UTC, hariclerry commented
Hello @Angamanga, thanks for the feedback and guide. However, do I need to make the changes in the file you pointed out: https://github.com/ushahidi/platform-pattern-library/blob/master/assets/sass/5_layouts/_layout-d.scss#L42? I thought it would be this file:  /assests/sass/utils/_helpers.scss, since it is the .right class which is responsible for positioning buttons. I made some changes, please take a look and advice accordingly. Thanks

2020-11-20 14:07 UTC, merged